### ISSUE TITLE
Generate Board of Directors Bios

### ISSUE THREAD

**Issue by placer14** [nationofmakers/nationofmakers.github.io#1]
Once we are aware of the Board of Directors, summary bios need to be generated.

They are:
**Harley DuBois** - Co-Founder of Burning Man, Board member of Burning Man and among other things has served as the city manager for Black Rock City for 10 years and is the co-founder of the Black Rock Arts Foundation.
**Pamela L. Jennings** - is currently a Professor of Innovation and Entrepreneurship in the Faculty of Business in the College of Arts, Sciences, Business and Education at Winston State Salem University and was formerly the Director of the Center for Design Innovation, a collaboration between Winston-Salem State University, the UNC-School of the Arts and Forsyth Technical Community College.
**Adam Savage**

Need 100-200 words about person's accomplishments and what they bring to the table as a NoM Board member.
Need a photo of the **member's head** that is at least 800px x 800px

**Comment by chaosbuster** [comment]
Need to add to the three Elected Board of Director's members to the website.
