### ISSUE TITLE
About page layout

### ISSUE THREAD

**Issue by placer14** [nationofmakers/nationofmakers.github.io#17]
The About page represents a 10k foot summary on the Nation of Makers. It will consist of the following content:

- Mission (#25)
- Vision (#25)
- Values (#25)
- History (#15)
- Press Coverage (#16)

Some of these sections have other issues open to gather their copy/content and should be coordinated appropriately.

**Comment by danawoodman** [comment]
Right now this is in the home page, so closing for now
