### ISSUE TITLE
Merge issues with existing website repository 

### ISSUE THREAD

**Issue by fredfalcon** [nationofmakers/nationofmakers.github.io#18]
We started working on the website here https://github.com/nationofmakers/nationofmakers.github.io would be good if we merge into one.

**Comment by placer14** [comment]
Happy to bring them over here. I didn't have access to the the Projects, Milestones and Labels on the old repo so I started this to be productive. I have no problem moving issues and repo content over.

**Comment by placer14** [comment]
I've reviewed the issues over there.
- Slack logging is enabled at slack.nation-of-makers.com
- Consensus forking repos should be an MCP document instead of attached to this repo
- Upload nice design is captured in #21 
- Creating a logo is captured in #4 

Closing as resolved.
