### ISSUE TITLE
Generate FAQ Content

### ISSUE THREAD

**Issue by placer14** [nationofmakers/nationofmakers.github.io#19]
What are the most important questions to ask?
Answers?

So far:
- how do I get involved?
- what kind of orgs/people are welcome?
- what does membership get me?
- Is NOM sponsored by the government, Whitehouse, or President?
- What will happen to the NOM organization after Trump is inaugurated?
- Can I donate to NOM, and are donations tax-deductible?
- Can NOM help me start/host a makerfaire in my town?

**Comment by danawoodman** [comment]
Some:
- how do I get involved?
- what kind of orgs/people are welcome?
- what does membership get me?

**Comment by tanju-b** [comment]
- Is NOM sponsored by the government, Whitehouse, or President?
- What will happen to the NOM organization after Trump is inaugurated?
- Can I donate to NOM, and are donations tax-deductible?
- Can NOM help me start/host a makerfaire in my town?

**Comment by danawoodman** [comment]
Good questions @tanju-b. If someone wants to start an FAQ on the about page that would be groovy

**Comment by chaosbuster** [comment]
Differences in terminology used. Descriptions of the different types of spaces and put on NOM website.

**Comment by tanju-b** [comment]
so I can start a FAQ page, but not sure what to do about formatting...should I just start one in markdown or plain text?

Nevermind, I just starting one in markdown

**Comment by tanju-b** [comment]
ok, see PR #41
