### ISSUE TITLE
Spike static site framework

### ISSUE THREAD

**Issue by placer14** [nationofmakers/nationofmakers.github.io#21]
Stand up a framework for the site that allows simple content management via github.com repos and little management of the generation pipeline (if any needed).

**Comment by danawoodman** [comment]
Why not use the built in Jekyll engine?

**Comment by fredfalcon** [comment]
Jekyll engine will be perfect

**Comment by placer14** [comment]
Jekyll seems apropos. Anyone have experience with Jekyll and want to test on a branch?

**Comment by danawoodman** [comment]
Github supports it out of the gate but I honestly don't have experience with it

**Comment by fredfalcon** [comment]
I've used it for one project... can we go plain static for now like we started?

**Comment by danawoodman** [comment]
@seanauriti by plain static you mean just pure HTML? I want people to submit copy and at least having a Markdown -> HTML conversion process would be great if possible

**Comment by fredfalcon** [comment]
Yes, kind of like what we have here - https://github.com/nationofmakers/nationofmakers.github.io - Markdown -> HTML sounds good, I'll re-open...

**Comment by danawoodman** [comment]
Sweet, that's all I think we need:
- A decent design
- Good, useful copy
- An easy way to submit changes

**Comment by placer14** [comment]
@seanauriti I think we'll go with Jekyll which can produce a static site similar to what's shown in the repo.

@danawoodman We have issues for design and useful copy. As far as easy change process... I think it'll work like this:
1. Github supports all text editing directly on github.com. Open any existing file and click the edit button as shown below...
   <img width="541" alt="nationofmakers_github_io_readme_md_at_master_ _nationofmakers_nationofmakers_github_io" src="https://cloud.githubusercontent.com/assets/305332/20005279/bdce5630-a267-11e6-9f96-3d7c2fbd5c22.png">
   You could also start a new file by opening an existing folder and clicking "Create new file" or "Upload files".
2. Make changes and then scroll down to the bottom to describe your changes (less than 80 characters in the title, and a more detailed description if requred past 80 chars). Click "Propose file change". This will create a forked repo on your account if it doesn't already exist, create a new branch called "patch-_n_" and offer to open the Pull Request for you.
3. Click the green "Create Pull Request" button.
4. Someone on the Website team will validate/merge the PR. (Another process.)

We can wrap all the Jekyll handling, site building/modifications, complexity in step 4.

**Comment by danawoodman** [comment]
Sounds great @placer14. Maybe you could add this to the README?

**Comment by placer14** [comment]
Delivered in 3d23b25

**Comment by placer14** [comment]
Until the repo name is updated, we can see the site at https://nationofmakers.github.io/website/
