### ISSUE TITLE
Formalize NoM identity

### ISSUE THREAD

**Issue by placer14** [nationofmakers/nationofmakers.github.io#22]
Need a color scheme and brand identity which helps communicate our mission, vision and values. This color scheme and identity should be used consistently across mediums.

Deliverables out of this should include:

- vector CMYK NoM logo
- vector B&W NoM logo
- color palette (with identified/consistent primary, secondary, and maybe tertiary color identified)

Please attach files and details directly to this issue.

**Comment by placer14** [comment]
I think we urgently need to solve whether we need to generate new identity/branding assets for NoM. @danawoodman How likely is it we'll be able to use the existing NoM.org assets for the new org/site?

**Comment by danawoodman** [comment]
We have all the assets from the original organization to use. For the short term we can use existing ones but I am of the opinion that we should create a custom brand around the new organization

**Comment by danawoodman** [comment]
Going to assign this to Bergen for help

**Comment by BeeLucid** [comment]
Happy to take point on this. :)
