### ISSUE TITLE
Design NoM site UI/UX

### ISSUE THREAD

**Issue by placer14** [nationofmakers/nationofmakers.github.io#23]
The design of the site should allow simple navigation, easy readability of content, quick navigation to key pages, and incorporate the brand and identity of the NoM (#22).

The deliverables would be sufficient instruction and assets to produce an HTML/CSS/JS shell of the NoM website. Design and styles should account for different content included throughout the site and "comfortably" accommodate that content. This includes basic content elements as well (p, div, h1-h6, pre, blockquote, img, strong, em, etc.)

**Comment by fredfalcon** [comment]
How about re-using some of the existing assets from http://www.nationofmakers.org/ ?
