### ISSUE TITLE
Wrap static site build tools into container

### ISSUE THREAD

**Issue by placer14** [nationofmakers/nationofmakers.github.io#24]
To make the tools easier to maintain and more portable for others to use, we should put all of the tools required to manage the static site generation and related tasks into a self-sufficient container (Docker, pls?) for use by the team.

Deliverables include instructions for the use of the container and it's contents.

**Comment by hamitron** [comment]
is there talk about using a stack?  Rails, Node, etc?

**Comment by adamobeng** [comment]
@placer14 Is there in fact a build process at the moment? It looks like the HTML files are being written manually.

**Comment by stevegt** [comment]
At the moment, for the interim site, the files are static HTML/CSS.  As long as we're hosting on github, the stack is likely to be jekyll.  In that case, a container would help with local testing.
