### ISSUE TITLE
Generate Transition Team Bios

### ISSUE THREAD

**Issue by placer14** [nationofmakers/nationofmakers.github.io#3]
- [ ] 100-150 word summary
- [ ] photo at least 800px width by 800px height
- [ ] email address (optional)
- [ ] canonical url(s) (optional)

Team Bios needed from
- Bergen
- Chad 
- Dana
- Dorothy
- Ian
- Kari 
- Kipp
- Steph

**Comment by danawoodman** [comment]
Can use from here https://docs.google.com/document/d/16GJSqo-5l45ZNQ_LTjZN5wTy-EdEcSHz0FiyuB0T86c

**Comment by danawoodman** [comment]
Added!
