### ISSUE TITLE
BUG: Newsletter Signup Mailchimp pointing to incorrect address

### ISSUE THREAD

**Issue by AWickedPixel** [nationofmakers/nationofmakers.github.io#40]
The Mailchimp newsletter signup and confirmation email are pointing to `nation-of-makers.com` rather than current site.

**Comment by stevegt** [comment]
@PushyPixl We think we've got this fixed (@danawoodman FTW!).  If I'm understanding the bug correctly I can't think of any way to check the confirmation email though without subscribing an extra email address.  The "newsletter signup" text you're talking about is where?

**Comment by danawoodman** [comment]
Yes, this was fixed by moi 😸
