### ISSUE TITLE
Put email link below board section

### ISSUE THREAD

**Issue by mkenigson** [nationofmakers/nationofmakers.github.io#56]
Per Dorothy:

I like the new contact us button :slightly_smiling_face: If it won't make you hate me, is there any way we can move it below the Board of Directors' pictures? It kind of looks random now that it's not a contact the Board button.... _is going away now so I can stop adding work for you all_

**Comment by stevegt** [comment]
This is *almost* done.  We've moved it to the "Stay Tuned" section, still needs a layout tweak.

**Comment by stevegt** [comment]
PR #64 makes this good enough, so closing this.  Related #54 still open.
